[application]
    key = "../server.key"
    crt = "../server.crt"
    log_location = "app.log"
    log_level = 9
[tcp_cli_test]
    client = "true"
    type = "tcp"
    listen = "127.0.0.1:8080"
    connect = "127.0.0.1:4443"
[tcp_srv_test]
    client = "false"
    type = "tcp"
    listen = "127.0.0.1:4443"
    connect = "185.192.112.25:80"
